version: "3"

services:

  scylla1:
    container_name: scylla1
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla1 --smp 1 --overprovisioned 1
    volumes:
      - "/var/lib/scylla/node1:/var/lib/scylla"
      - "/var/log/scylla/node1:/var/log/scylla"
    expose:
      - 9042
    ports:
      - "19042:9042"

  scylla2:
    container_name: scylla2
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla1 --smp 1 --overprovisioned 1
    depends_on:
      - scylla1
    volumes:
      - "/var/lib/scylla/node2:/var/lib/scylla"
      - "/var/log/scylla/node2:/var/log/scylla"
    expose:
      - 9042
    ports:
      - "29042:9042"

  scylla3:
    container_name: scylla3
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla1 --smp 1 --overprovisioned 1
    depends_on:
      - scylla1
    volumes:
      - "/var/lib/scylla/node3:/var/lib/scylla"
      - "/var/log/scylla/node3:/var/log/scylla"
    expose:
      - 9042
    ports:
      - "39042:9042"
